modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"

[[mixins]]
config = "emi.mixins.json"

[[mods]]
modId = "emi"
version = "${version}"
displayName = "EMI"
authors = "Emi"
description = '''
A featureful and accessible item and recipe viewer
'''

[[dependencies.emi]]
modId = "neoforge"
type = "required"
versionRange = "[26.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.emi]]
modId = "minecraft"
type = "required"
versionRange = "[26.2,)"
ordering = "NONE"
side = "BOTH"
